### ISSUE TITLE
there is no face_recognition module

### ISSUE THREAD

**Issue by subhunt2003** [beemsoft/lego-mindstorms-51515-jetson-nano#1]
there is no face_recognition module.

so that importing face_recognition on line 38 of demo.py is triggering error.

**Comment by beemsoft** [comment]
Thanks for trying this demo!
I've added the face recognition section to the Readme.
Please try again!

**Comment by subhunt2003** [comment]
I tried compiling dlib by CMake from scretch per its official instruction but the build did not enable CUDA for whatever reason. the command "dlib.DLIB_USE_CUDA" returns false.

Your method "sudo pip3 install Cython face_recognition" is much easier and works great on Jetson Nano.

thanks and keep on good work!
